apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: loadbalancer
  name: loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loadbalancer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/project-tf-default: "true"
        io.kompose.service: loadbalancer
    spec:
      containers:
        - image: loadbalancer-i
          name: loadbalancer
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
      restartPolicy: Always
