apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: web1
  name: web1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/project-tf-default: "true"
        io.kompose.service: web1
    spec:
      containers:
        - image: gen-i
          name: data-gen
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
      restartPolicy: Always
