apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: web3
  name: web3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web3
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/project-tf-default: "true"
        io.kompose.service: web3
    spec:
      containers:
        - image: iapp_2-i
          name: iapp-2
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
