name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r book_service/requirements.txt
        pip install -r author_service/requirements.txt
        pip install -r inventory_service/requirements.txt
        pip install -r order_service/requirements.txt

    - name: Run tests
      run: |
        pytest book_service/tests
        pytest author_service/tests
        pytest inventory_service/tests
        pytest order_service/tests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t your-dockerhub-username/book-service ./book_service
        docker build -t your-dockerhub-username/author-service ./author_service
        docker build -t your-dockerhub-username/inventory-service ./inventory_service
        docker build -t your-dockerhub-username/order-service ./order_service
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push your-dockerhub-username/book-service
        docker push your-dockerhub-username/author-service
        docker push your-dockerhub-username/inventory-service
        docker push your-dockerhub-username/order-service
